name: Deploy Backend

on:
  push:
    branches:
      - haegi # 브랜치명 맞춰서 사용

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot App
        run: ./gradlew build -x test

      - name: Copy build file to server via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 8807
          source: 'build/libs/*.jar'
          target: '/home/haegi/mbn-back'

      - name: Deploy with SSH and PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 8807
          script: |
            cd /home/haegi/mbn-back
            JAR_NAME=$(ls build/libs/*.jar | head -n 1)

            pm2 delete mbn-back || true

            pm2 start "java \
              -DHAEGI_SERVER_MBN_URL='${{ secrets.HAEGI_SERVER_MBN_URL }}' \
              -DHAEGI_SERVER_USERNAME='${{ secrets.HAEGI_SERVER_USERNAME }}' \
              -DHAEGI_SERVER_PASSWORD='${{ secrets.HAEGI_SERVER_PASSWORD }}' \
              -DJWT_SECRET='${{ secrets.JWT_SECRET }}' \
              -DKAKAO_CLIENT_ID='${{ secrets.KAKAO_CLIENT_ID }}' \
              -DKAKAO_REDIRECT_URL='${{ secrets.KAKAO_REDIRECT_URL }}' \
              -DFRONT_DOMAIN_URL='${{ secrets.FRONT_DOMAIN_URL }}' \
              -jar $JAR_NAME --server.port=3334" --name mbn-back

            pm2 save
