name: Deploy Backend

on:
  push:
    branches:
      - haegi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Spring Boot App
        run: ./gradlew build -x test

      - name: Copy JAR and ecosystem.config.js to server via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 8807
          source: |
            build/libs/*.jar
            ecosystem.config.js
          target: /home/haegi/mbn-back

      - name: Deploy on server using PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 8807
          script: |
            cd /home/haegi/mbn-back

            export HAEGI_SERVER_MBN_URL=${{ secrets.HAEGI_SERVER_MBN_URL }}
            export HAEGI_SERVER_USERNAME=${{ secrets.HAEGI_SERVER_USERNAME }}
            export HAEGI_SERVER_PASSWORD=${{ secrets.HAEGI_SERVER_PASSWORD }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}
            export KAKAO_REDIRECT_URL=${{ secrets.KAKAO_REDIRECT_URL }}
            export FRONT_DOMAIN_URL=${{ secrets.FRONT_DOMAIN_URL }}

            pm2 delete mbn-back || true
            pm2 start ecosystem.config.js
            pm2 save
